name: Security scans (pip-audit + Trivy)

on:
  pull_request:
    paths:
      - "requirements.txt"
      - "uv.lock"
      - "pyproject.toml"
      - "Dockerfile"
      - "docker/**"
  schedule:
    - cron: "0 3 * * 1" # Mondays 03:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: security-scans-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pip-audit:
    name: pip-audit (deps)
    if: ${{ github.actor != 'nektos/act' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python + uv (cached)
        uses: ./.github/actions/setup-uv
      #- name: Seed pip in .venv
      #  run: uv venv --seed
      - name: pip-audit via Makefile
        run: make pip-audit

  trivy-fs:
    name: Trivy FS (vuln+config+secrets)
    if: ${{ github.actor != 'nektos/act' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy repo scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
